import os
import sys
from typing import Iterable

FILENAMES = {
    '<CER> 武器': [
        'WeaponName.fmg.txt',
        'WeaponName_dlc01.fmg.txt',
    ],
    '<CER> 防具': [
        'ProtectorName.fmg.txt',
        'ProtectorName_dlc01.fmg.txt',
    ],
    '<CER> 护符': [
        'AccessoryName.fmg.txt',
        'AccessoryName_dlc01.fmg.txt',
    ],
    '<CER> 物品': [
        'GoodsName.fmg.txt',
        'GoodsName_dlc01.fmg.txt',
    ],
    '<CER> 战灰': [
        'ArtsName.fmg.txt',
        'ArtsName_dlc01.fmg.txt',
        'GemName.fmg.txt',
    ],
}
OFFSETS = {
    '<CER> 武器': 0x0,
    '<CER> 防具': 0x10000000,
    '<CER> 护符': 0x20000000,
    '<CER> 物品': 0x40000000,
    '<CER> 战灰': 0x80000000,
}

def convert_file_content_to_dict(cont: str, offset: int = 0x0, is_weapon: bool = False) -> dict[str, int]:
    dct = {}
    for line in cont.splitlines():
        if line == '' or line[0] != '=':
            continue
        # Assume format:
        # = <ID>:"<NAME>"
        id_s, name = line[2:-1].split(':"')
        if is_weapon and not id_s.endswith('0000'):
            continue
        dct[name] = int(id_s) + offset
    return dct

def write_to_yaml(fn: str, dct: dict[str, dict[str, int]]):
    with open(fn, 'w', encoding='utf-8') as f:
        f.write('''\
#########################################
#  Generated by convert_item_ids_cer.py.
#  DO NOT EDIT.
#########################################
''')
        for k, v in dct.items():
            f.write('"%s":\n' % k)
            for kk, vv in v.items():
                f.write('  "%s": %d\n' % (kk, vv))

def main(argv: Iterable[str] | None = None):
    root = sys.argv[1] if argv is None else argv[1]
    categories = FILENAMES.keys()
    dct = {}
    for cat in categories:
        dd = {}
        is_weapon = (cat == '<CER> 武器')
        for fn in FILENAMES[cat]:
            with open(os.path.join(root, fn), 'r', encoding='utf-8') as f:
                cont = f.read()
            dd.update(convert_file_content_to_dict(cont, OFFSETS[cat], is_weapon))
        dct[cat] = dd
    write_to_yaml('item_ids_cer.yml', dct)
    # return dct

if __name__ == '__main__':
    main()