name: Build
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lints"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (
        github.event_name == 'workflow_run' && 
        github.event.workflow_run.conclusion == 'success' && 
        github.event.workflow_run.event == 'push' && 
        github.event.workflow_run.head_branch == 'main'
      )
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          submodules: recursive

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --target x86_64-pc-windows-msvc --profile minimal

      - name: Distribution build
        run: cargo xtask dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jdsd_er_practice_tool
          path: target/dist/jdsd_er_practice_tool.zip
