name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --target x86_64-pc-windows-msvc --profile minimal

      - name: Distribution build
        run: cargo xtask dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jdsd_er_practice_tool_zhCN_withCER
          path: target/dist/jdsd_er_practice_tool_zhCN_withCER.zip
